export const GET_SERVER_INFO = 'GET_SERVER_INFO';
export const SET_SERVER_INFO = 'SET_SERVER_INFO';
export const SERVER_INFO_LOADING = 'SERVER_INFO_LOADING';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Basic channel info action types. 
export const GET_CHANNELDI1_INFO = 'GET_CHANNELDI1_INFO';
export const SET_CHANNELDI1_INFO = 'SET_CHANNELDI1_INFO';
export const SET_DICHANNEL_NAME = 'SET_DICHANNEL-NAME';
export const SET_DICHANNEL_ALIASOFF = 'SET_DICHANNEL_ALIASOFF';
export const SET_DICHANNEL_ALIASON = 'SET_DICHANNEL_ALIASON';
export const SET_DICHANNEL_STATUS = 'SET_DICHANNEL_STATUS';
//export const APPLY_TO_ALL_DI = 'APPLY_TO_ALL_DI';